---
apiVersion: v1
kind: Secret
metadata:
  name: env-astrology-api-secrets
  namespace: astrolumina-dev
  labels:
    app.kubernetes.io/part-of: astrolumina
    app.kubernetes.io/component: astrology-api
    environment: development
type: Opaque
stringData:
  ASTROLOGER_API_KEY: "6f3a5e9544mshd7e0a65190501c3p17f451jsn323abc5466e5"
  SENTRY_DSN: "https://55f378ef29cb906438317cd13705730f@o4508774232948736.ingest.de.sentry.io/4508776705622096"

---
apiVersion: v1
kind: Secret
metadata:
  name: env-booking-api-secrets
  namespace: astrolumina-dev
  labels:
    app.kubernetes.io/part-of: astrolumina
    app.kubernetes.io/component: booking-api
    environment: development
type: Opaque
stringData:
  CALCOM_API_KEY: "cal_live_a0220066e8130b3dcb1da48c039d589f"
  RESEND_API_KEY: "re_Yo6EjLos_LP4jZ69mkqauiknMbQxpi3M5"
  D1_ACCOUNT_ID: "a5af9ec5476686f5d534c98f596d9f16"
  D1_API_TOKEN: "cfut_qn3iNqpYYxSnQoJj4W5mA5TVFKFr0FcxNRWEhLIK6e3991f7"
  D1_DATABASE_ID: "e7939548-297e-4f61-a39b-63fb91f62748"
  SENTRY_DSN: "https://a27bb0225d8383641ed0efd98ea602e9@o4508774232948736.ingest.de.sentry.io/4511088669294672"

---
apiVersion: v1
kind: Secret
metadata:
  name: env-payment-api-secrets
  namespace: astrolumina-dev
  labels:
    app.kubernetes.io/part-of: astrolumina
    app.kubernetes.io/component: payment-api
    environment: development
type: Opaque
stringData:
  STRIPE_SK: "sk_test_51QsKuwI8IlTXEO0J7GYkGORq736TunFslDCkAb6tceDDStwU7Nq6UOHx9CnbkmTJWA2WEERjA2JtRcLTyWfeXzzY00yursmiJq"
  SENTRY_DSN: "https://0aa1447857eff041fbbf6908f3ec300c@o4508774232948736.ingest.de.sentry.io/4511072603406416"
