apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: astrolumina-staging

resources:
  - 10-frontend-deployment.yaml
  - 11-frontend-service.yaml
  - 20-astrology-api-deployment.yaml
  - 21-astrology-api-service.yaml
  - 30-booking-api-deployment.yaml
  - 31-booking-api-service.yaml
  - 40-payment-api-deployment.yaml
  - 41-payment-api-service.yaml
  - 50-ingress.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: astrolumina
  variant: green
