apiVersion: v1
kind: Service
metadata:
  name: frontend-blue
  namespace: astrolumina-prod
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: astrolumina
    app.kubernetes.io/component: frontend
    environment: production
    variant: blue
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/component: frontend
    variant: blue
