apiVersion: v1
kind: Service
metadata:
  name: booking-api-blue
  namespace: astrolumina-prod
  labels:
    app.kubernetes.io/name: booking-api
    app.kubernetes.io/part-of: astrolumina
    app.kubernetes.io/component: booking-api
    environment: production
    variant: blue
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3033
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: booking-api
    app.kubernetes.io/component: booking-api
    variant: blue
