apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 10-frontend-deployment.yaml
  - 20-astrology-api-deployment.yaml
  - 30-booking-api-deployment.yaml
  - 40-payment-api-deployment.yaml
